"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { fetchHypotheses, Hypothesis } from "@/lib/api";

export default function HypothesesPage() {
  const [hypotheses, setHypotheses] = useState<Hypothesis[]>([]);
  const [filter, setFilter] = useState<string>("ALL");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchHypotheses()
      .then((data) => setHypotheses(data))
      .catch((err) => console.error("Failed to load hypotheses:", err))
      .finally(() => setLoading(false));
  }, []);

  const filtered = hypotheses.filter((h) => {
    if (filter === "ALL") return true;
    return h.status === filter;
  });

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-slate-800 pb-4">
        <div>
          <h1 className="text-xl font-bold text-slate-100 flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-500" />
            Hypotheses & Audit Records
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Complete database audit log of pre-trade contracts generated by the LLM agent.
          </p>
        </div>

        {/* Status Filter Tabs */}
        <div className="flex items-center gap-1.5 bg-slate-900/80 p-1 rounded-lg border border-slate-800 text-xs">
          {["ALL", "ACTIVE", "PENDING", "CLOSED", "ABORTED"].map((tab) => (
            <button
              key={tab}
              onClick={() => setFilter(tab)}
              className={`px-3 py-1.5 rounded transition-all font-semibold ${
                filter === tab
                  ? "bg-emerald-600 text-slate-950 shadow"
                  : "text-slate-400 hover:text-slate-200"
              }`}
            >
              {tab}
            </button>
          ))}
        </div>
      </div>

      {/* Main Table */}
      <div className="terminal-card p-6">
        {loading ? (
          <div className="py-12 text-center text-slate-400 text-xs flex items-center justify-center gap-2">
            <span className="w-4 h-4 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin" />
            Loading hypotheses from Supabase...
          </div>
        ) : filtered.length === 0 ? (
          <div className="py-12 text-center text-slate-500 text-xs border border-dashed border-slate-800 rounded">
            No hypotheses matching status "{filter}".
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-slate-800 text-slate-400 uppercase">
                  <th className="py-3 px-3">Created</th>
                  <th className="py-3 px-3">Symbol</th>
                  <th className="py-3 px-3">Side</th>
                  <th className="py-3 px-3">Qty</th>
                  <th className="py-3 px-3">Entry Price</th>
                  <th className="py-3 px-3">Target Price</th>
                  <th className="py-3 px-3">Stop Loss</th>
                  <th className="py-3 px-3">Status</th>
                  <th className="py-3 px-3 text-right">Details</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60">
                {filtered.map((hyp) => (
                  <tr key={hyp.id} className="hover:bg-slate-900/50">
                    <td className="py-3.5 px-3 text-slate-400 whitespace-nowrap">
                      {new Date(hyp.created_at).toLocaleString([], {
                        month: "short",
                        day: "numeric",
                        hour: "2-digit",
                        minute: "2-digit",
                      })}
                    </td>
                    <td className="py-3.5 px-3 font-bold text-emerald-400">{hyp.symbol}</td>
                    <td className="py-3.5 px-3">
                      <span
                        className={`px-2 py-0.5 rounded text-[10px] uppercase font-bold ${
                          hyp.side === "buy"
                            ? "bg-emerald-950 text-emerald-400 border border-emerald-800"
                            : "bg-red-950 text-red-400 border border-red-800"
                        }`}
                      >
                        {hyp.side}
                      </span>
                    </td>
                    <td className="py-3.5 px-3 text-slate-300">{hyp.qty}</td>
                    <td className="py-3.5 px-3 text-slate-300">
                      ${hyp.entry_price ? Number(hyp.entry_price).toFixed(2) : "Market"}
                    </td>
                    <td className="py-3.5 px-3 text-emerald-400 font-medium">
                      ${Number(hyp.target_price).toFixed(2)}
                    </td>
                    <td className="py-3.5 px-3 text-red-400 font-medium">
                      ${Number(hyp.stop_loss_price).toFixed(2)}
                    </td>
                    <td className="py-3.5 px-3">
                      <span
                        className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                          hyp.status === "ACTIVE"
                            ? "bg-emerald-950 text-emerald-400 border border-emerald-800 animate-pulse"
                            : hyp.status === "PENDING"
                            ? "bg-amber-950 text-amber-400 border border-amber-800"
                            : hyp.status === "CLOSED"
                            ? "bg-slate-800 text-slate-300 border border-slate-700"
                            : "bg-red-950 text-red-400 border border-red-800"
                        }`}
                      >
                        {hyp.status}
                      </span>
                    </td>
                    <td className="py-3.5 px-3 text-right">
                      <Link
                        href={`/hypotheses/${hyp.id}`}
                        className="bg-slate-800 hover:bg-slate-700 text-slate-200 px-3 py-1 rounded border border-slate-700 transition-all text-[11px]"
                      >
                        Audit Log &rarr;
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
